{
 "title": "Docker Spark Monitoring",
 "tags": [
  "spark",
  "docker"
 ],
 "time": { "from": "2025-09-06T15:14:12.595Z", "to": "2025-09-06T15:14:12.595Z" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Driver IP Address",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"spark-master\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Driver Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "spark_running_applications", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "애플리케이션 처리량",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 8, "y": 1 },
   "targets": [
    { "expr": "spark_running_applications", "legendFormat": "__auto" },
    { "expr": "spark_completed_applications ", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Applications",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "spark_total_applications", "legendFormat": "__auto" }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Spark Master Workers",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "metrics_master_workers_Number{job=\"spark-master\"}",
       "legendFormat": "Workers"
      }
     ]
    },
    {
     "title": "Active Applications",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "metrics_master_apps_Value{job=\"spark-master\"}",
       "legendFormat": "Apps"
      }
     ]
    },
    {
     "title": "JVM Heap Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_bytes_used{area=\"heap\",job=\"spark-master\"}",
       "legendFormat": "Master Heap"
      },
      {
       "expr": "jvm_memory_bytes_used{area=\"heap\",job=\"spark-worker\"}",
       "legendFormat": "Worker Heap"
      }
     ]
    }
   ]
  }
 ]
}