{
 "title": "Apache Spark - Performance Metrics",
 "description": "Monitors spark metrics using Prometheus in Kubernetes",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "app_id",
    "query": {
     "query": "label_values(spark_executor_active_tasks,app_id)"
    }
   },
   {
    "name": "app_name",
    "query": {
     "query": "label_values(spark_executor_active_tasks{app_name=\"GDELT Silver Processor\"},app_name)"
    }
   },
   { "name": "query0" },
   { "name": "query1" }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Executor Shuffle I/O",
   "type": "timeseries",
   "description": "Executor Shuffle (bytes/sec)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(spark_executor_shuffle_read_bytes{app_id=~\"$app_id\"}[$__rate_interval])",
     "legendFormat": "{{executor_id}} - Read"
    },
    {
     "expr": "rate(spark_executor_shuffle_write_bytes{app_id=~\"$app_id\"}[$__rate_interval])",
     "legendFormat": "{{executor_id}} - Write"
    }
   ]
  },
  {
   "title": "Executor Active Tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "spark_executor_active_tasks{app_id=~\"$app_id\"}",
     "legendFormat": "{{executor_id}}"
    }
   ]
  },
  {
   "title": "Driver Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Running Applications",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 10 },
   "repeat": "Pod",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "spark_running_applications", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Succeeded Jobs & Stage Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 4, "y": 10 },
   "repeat": "Pod",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "spark_driver_succeeded_jobs{app_id=~\"$app_id\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "spark_driver_active_stages{app_id=~\"$app_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running Jobs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "spark_driver_running_jobs{app_id=~\"$app_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Jobs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "spark_driver_failed_jobs{app_id=~\"$app_id\"}"
    }
   ]
  },
  {
   "title": "Driver Resource usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Driver Memory Usage",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": " sum (container_memory_working_set_bytes{pod_name=~\"^$Pod$\"}) /sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"}) * 100"
      }
     ]
    },
    {
     "title": "Executor Memory Usage",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": " sum (container_memory_working_set_bytes{pod_name=~\"^$executor$\"}) /sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"}) * 100"
      }
     ]
    },
    {
     "title": "Used",
     "type": "stat",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{pod_name=~\"^$Pod$\"})"
      }
     ]
    },
    {
     "title": "Used",
     "type": "stat",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{pod_name=~\"^$executor$\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Driver CPU / Memory  usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Driver Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "repeat": "Pod",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\", instance=\"spark-custom-exporter:9191\", jmx_source=\"driver\",job=\"spark-custom-exporter\"}",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Driver CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{jmx_source=\"driver\"}[$__rate_interval])",
     "legendFormat": "Used CPU : {{pod_name}}"
    }
   ]
  },
  {
   "title": "Driver GC : Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{jmx_source=\"driver\"}[$__rate_interval])",
     "legendFormat": "{{ gc }}"
    }
   ]
  },
  {
   "title": "Executor CPU /Memory Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Executor :  Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "spark_executor_memory_used_bytes{app_id=~\"$app_id\"}",
     "legendFormat": "{{ executor_id }} "
    }
   ]
  },
  {
   "title": "Executor  :  CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{jmx_source=\"executor\"}[$__rate_interval])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Executor GC : Seconds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{jmx_source=\"executor\"}[$__rate_interval])",
     "legendFormat": "{{ instance}}"
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Driver Network I/O",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{pod_name=~'$Pod'}[2m])) by (pod_name)",
       "legendFormat": "{{ pod_name }}  Received"
      },
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{pod_name=~'$Pod'}[2m])) by (pod_name)",
       "legendFormat": "{{ pod_name }}  Transmitted"
      }
     ]
    },
    {
     "title": "Executor Network Transmitted",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 10, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{pod_name=~'$executor',kubernetes_io_hostname=~\"$Node\"}[2m])) by (pod_name,kubernetes_io_hostname)",
       "legendFormat": "{{ pod_name }} {{kubernetes_io_hostname}} Transmitted"
      }
     ]
    },
    {
     "title": "Executor Network Received",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{pod_name=~'$executor',pod_name!=\"pod\",kubernetes_io_hostname=~\"$Node\"}[2m])) by (pod_name,kubernetes_io_hostname)",
       "legendFormat": "{{ pod_name }} {{kubernetes_io_hostname}}  Received"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Disk Read Bytes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_reads_bytes_total{pod_name=~\"$Pod|$executor\",device=~\"/dev/sd[a|c|e]\"}[2m])) by (pod_name,device)",
       "legendFormat": "{{pod_name }} {{device}} Read"
      }
     ]
    },
    {
     "title": "Disk Writes Bytes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_writes_bytes_total{pod_name=~\"$Pod|$executor\",device=~\"/dev/sd[a|c|e]\"}[2m])) by (pod_name,device)",
       "legendFormat": "{{pod_name }}{{device}} Write"
      }
     ]
    }
   ]
  },
  {
   "title": "Spark External Shuffle",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Spark Shuffle Network Transmitted",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{pod_name=~'.*shuffle.*',kubernetes_io_hostname=~\"$Node\"}[2m])) by (pod_name,kubernetes_io_hostname)",
       "legendFormat": "{{ pod_name }} {{kubernetes_io_hostname}} Transmitted"
      }
     ]
    },
    {
     "title": "Spark Shuffle Network Received",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{pod_name=~'.*shuffle.*',pod_name!=\"pod\",kubernetes_io_hostname=~\"$Node\"}[2m])) by (pod_name,kubernetes_io_hostname)",
       "legendFormat": "{{ pod_name }} {{kubernetes_io_hostname}}  Received"
      }
     ]
    },
    {
     "title": "Disk Read Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_reads_bytes_total{pod_name=~\".*shuffle.*\",device=~\"/dev/sd[a|c|e]\"}[2m])) by (pod_name,device)",
       "legendFormat": "{{pod_name }} {{device}} Read"
      }
     ]
    },
    {
     "title": "Disk Writes Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_writes_bytes_total{pod_name=~\".*shuffle.*\",device=~\"/dev/sd[a|c|e]\"}[2m])) by (pod_name,device)",
       "legendFormat": "{{pod_name }}{{device}} Write"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Heap / Non - Heap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Heap Memory",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_bytes_used{name=~\"^$Pod$\",area=\"heap\"} ",
       "legendFormat": "{{ name }} "
      },
      {
       "expr": "jvm_memory_bytes_used{kubernetes_pod_name=~\"^$executor$\",area=\"heap\"}",
       "legendFormat": " {{ kubernetes_pod_name }} "
      }
     ]
    },
    {
     "title": "Non Heap Memory",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "jvm_memory_bytes_used{name=~\"$Pod\",area=\"nonheap\"}",
       "legendFormat": "{{ name }}"
      },
      {
       "expr": "jvm_memory_bytes_used{kubernetes_pod_name=~\"$executor\",area=\"nonheap\"}",
       "legendFormat": "{{kubernetes_pod_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Threads & Memory Pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Memory Pool",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_pool_bytes_used{kubernetes_pod_name=~\"$executor\"}) by (kubernetes_pod_name,pool)",
       "legendFormat": "{{ kubernetes_pod_name }} {{pool}}"
      },
      {
       "expr": "sum(jvm_memory_pool_bytes_used{name=~\"$Pod\"}) by (name,pool)",
       "legendFormat": "{{ name }} {{pool}}"
      }
     ]
    },
    {
     "title": "JVM Threads",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_threads_current{kubernetes_pod_name=~\"$executor\"}) by (kubernetes_pod_name)",
       "legendFormat": "{{ kubernetes_pod_name }}"
      },
      {
       "expr": "sum(jvm_threads_current{name=~\"$Pod\"}) by (name)",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Executor : Completed Tasks",
     "type": "graph",
     "gridPos": { "h": 9, "w": 10, "x": 6, "y": 59 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "spark_executor_executor_threadpool_completetasks{kubernetes_pod_name=~\"$executor\"}",
       "legendFormat": "{{ kubernetes_pod_name }}"
      },
      {}
     ]
    },
    {
     "title": "Executor : Active Tasks",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 59 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "spark_executor_executor_threadpool_activetasks{kubernetes_pod_name=~\"$executor\"}",
       "legendFormat": "{{ kubernetes_pod_name }}"
      },
      {}
     ]
    }
   ]
  },
  {
   "title": "Miscellaneous Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Executors Spawned",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(kube_pod_info{created_by_name=~\"$Pod\"})",
       "legendFormat": "Executor Counts "
      }
     ]
    },
    {
     "title": "Packets Dropped : Network",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 8, "y": 61 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "container_network_receive_packets_dropped_total{pod_name=~\"$Pod|$executor\"}",
       "legendFormat": "{{pod_name}} - Receive"
      },
      {
       "expr": "container_network_transmit_packets_dropped_total{pod_name=~\"$Pod|$executor\"}",
       "legendFormat": "{{pod_name}} - Transmit"
      }
     ]
    },
    {
     "title": "Kubernetes Pod Slice",
     "type": "table-old",
     "gridPos": { "h": 9, "w": 10, "x": 14, "y": 61 },
     "targets": [
      {
       "expr": "container_network_receive_bytes_total{pod_name=~\"$executor\"}"
      },
      {
       "expr": "container_network_receive_bytes_total{pod_name=~\"$Pod\"}"
      },
      {}
     ]
    }
   ]
  }
 ]
}