global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  # Kafka
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9404']
    scrape_interval: 30s
  
  - job_name: 'spark-custom-exporter'
    static_configs:
      - targets: ['spark-custom-exporter:9191']
    metrics_path: /metrics

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']