# 프로젝트명 (dbt_project.yml과 일치시켜야함)
analytics_dbt: 
  target: dev
  outputs:
    dev:
      # Spark 엔진 사용
      type: spark
      method: thrift
      host: spark-thrift-server
      port: 10001
      user: root
      auth: NOSASL
      schema: default
      http_path: cliservice
      
      # 연결 안정성을 위한 옵션
      connect_retries: 5
      connect_timeout: 60
      retry_all: true

    # PostgreSQL 설정
    postgres:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'postgres') }}"
      user: "{{ env_var('POSTGRES_USER', 'airflow') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'airflow') }}"
      port: "{{ env_var('POSTGRES_PORT', '5432') | int }}"
      dbname: "{{ env_var('POSTGRES_DB', 'airflow') }}"
      schema: gold_datamart # dbt가 모델을 생성할 기본 스키마
      threads: 4
      keepalives_idle: 0