---
# Kafka 모니터링을 위한 JMX Exporter 설정

rules:
  # === Kafka Broker & Server Metrics ===
  - pattern: "kafka.server<type=KafkaServer, name=(.+)><>Value"
    name: "kafka_server_$1"
    labels:
      job: "kafka"

  - pattern: "kafka.server<type=BrokerTopicMetrics, name=(.+)><>Count"
    name: "kafka_server_brokertopicmetrics_$1_total"
    type: COUNTER
    labels:
      job: "kafka"

  # === Topic별 상세 메트릭 ===
  - pattern: "kafka.server<type=BrokerTopicMetrics, name=(.+), topic=(.+)><>Count"
    name: "kafka_server_brokertopicmetrics_$1_total"
    type: COUNTER
    labels:
      job: "kafka"
      topic: "$2"

  # === Log & Partition Metrics ===
  - pattern: "kafka.log<type=Log, name=(.+), topic=(.+), partition=(.+)><>Value"
    name: "kafka_log_$1"
    labels:
      job: "kafka"
      topic: "$2"
      partition: "$3"

  # === Network & Request Metrics ===
  - pattern: "kafka.network<type=RequestMetrics, name=(.+), request=(.+)><>Count"
    name: "kafka_network_requestmetrics_$1_total"
    type: COUNTER
    labels:
      job: "kafka"
      request: "$2"

  # === JVM 메모리 (Heap/NonHeap) ===
  - pattern: "java.lang<type=Memory><>HeapMemoryUsage<name=(.+)>"
    name: "kafka_jvm_memory_heap_usage_$1"
    labels:
      job: "kafka"
  - pattern: "java.lang<type=Memory><>NonHeapMemoryUsage<name=(.+)>"
    name: "kafka_jvm_memory_nonheap_usage_$1"
    labels:
      job: "kafka"

  # === JVM 메모리 풀 (G1, Eden, Survivor 등) ===
  - pattern: "java.lang<type=MemoryPool, name=(.+)><>Usage<name=(.+)>"
    name: "kafka_jvm_memory_pool_usage_$2"
    labels:
      job: "kafka"
      pool_name: "$1"

  # === JVM GC (Garbage Collection) ===
  - pattern: "java.lang<type=GarbageCollector, name=(.+)><>Collection(Count|Time)"
    name: "kafka_jvm_gc_collection_$2_total"
    type: COUNTER
    labels:
      job: "kafka"
      gc_name: "$1"

lowercaseOutputName: true
lowercaseOutputLabelNames: true